import React, { useEffect, useMemo, useRef, useState } from "react";
import { createRoot } from "react-dom/client";
import { open } from "@tauri-apps/plugin-dialog";
import { convertFileSrc, invoke } from "@tauri-apps/api/core";
import ReactMarkdown from "react-markdown";
import rehypeHighlight from "rehype-highlight";
import remarkGfm from "remark-gfm";
import MarkdownEditor, { type MarkdownEditorHandle } from "./MarkdownEditor";
import { FocusModeToggle, NoteListItem, QuickSwitcher, ResizableSplit, TagCombobox, ViewModeControl } from "./components";
import "./styles.css";

type NoteSummary = { path: string; title: string; tags: string[]; updated: number; searchable_text: string; excerpt: string };
type NoteDocument = NoteSummary & { body: string; revision: string; created?: string; updated_at?: string };
type Filter = { type: "all" | "untagged" | "tag"; tag?: string };
type Conflict = { disk: NoteDocument; mine: NoteDocument };
type MarkdownNode = { type?: string; lang?: string | null; children?: MarkdownNode[] };
const libraryKey = "markdown-notes.library-path";
const pinnedKey = "markdown-notes.pinned";
const shortcut = navigator.platform.toLowerCase().includes("mac") ? "⌘" : "Ctrl+";

function formatDate(timestamp: number) { return new Intl.DateTimeFormat(undefined, { month: "short", day: "numeric" }).format(timestamp * 1000); }
function titleFromBody(body: string) { return body.match(/^#\s+(.+)$/m)?.[1]?.trim() || "Untitled"; }
function fileStem(path: string) { return path.split(/[\\/]/).pop()?.replace(/\.md$/i, "") || "Untitled"; }
function wikiTargets(body: string) { return [...body.matchAll(/\[\[([^\]|]+)(?:\|[^\]]+)?\]\]/g)].map(match => match[1].trim()); }

function App() {
  const [library, setLibrary] = useState<string | null>(localStorage.getItem(libraryKey));
  const [notes, setNotes] = useState<NoteSummary[]>([]); const [activePath, setActivePath] = useState<string | null>(null);
  const [note, setNote] = useState<NoteDocument | null>(null); const [filter, setFilter] = useState<Filter>({ type: "all" });
  const [query, setQuery] = useState(""); const [mode, setMode] = useState<"edit" | "preview" | "split">("edit");
  const [status, setStatus] = useState("Choose a notes folder to begin"); const [quickOpen, setQuickOpen] = useState(false);
  const [sidebarHidden, setSidebarHidden] = useState(false); const [conflict, setConflict] = useState<Conflict | null>(null);
  const [renameOpen, setRenameOpen] = useState(false); const [pinned, setPinned] = useState<string[]>(() => JSON.parse(localStorage.getItem(pinnedKey) || "[]"));
  const [focusMode, setFocusMode] = useState(false); const [tagInput, setTagInput] = useState("");
  const baseline = useRef<NoteDocument | null>(null); const editor = useRef<MarkdownEditorHandle>(null); const activePathRef = useRef<string | null>(null);

  const refresh = async (path = library) => { if (!path) return; try { const result = await invoke<NoteSummary[]>("load_library", { libraryPath: path }); setNotes(result); setStatus(`${result.length} ${result.length === 1 ? "note" : "notes"}`); } catch (error) { setStatus(`Could not read library: ${String(error)}`); } };
  useEffect(() => { void refresh(); }, [library]);
  useEffect(() => { activePathRef.current = activePath; }, [activePath]);
  useEffect(() => { localStorage.setItem(pinnedKey, JSON.stringify(pinned)); }, [pinned]);
  useEffect(() => { if (!activePath) { setNote(null); return; } void (async () => { try { const loaded = await invoke<NoteDocument>("read_note", { path: activePath }); baseline.current = loaded; setNote(loaded); setMode("edit"); } catch (error) { setStatus(`Could not open note: ${String(error)}`); } })(); }, [activePath]);
  useEffect(() => { setTagInput(""); }, [activePath]);
  useEffect(() => { if (!note || mode === "preview") return; const timer = window.setTimeout(() => void saveNote(note), 700); return () => window.clearTimeout(timer); }, [note?.body, note?.title, note?.tags.join("\0")]);
  useEffect(() => { const interval = window.setInterval(async () => { if (!library) return; await refresh(); if (note && baseline.current) { try { const disk = await invoke<NoteDocument>("read_note", { path: note.path }); if (disk.revision !== baseline.current.revision && (note.title !== baseline.current.title || note.body !== baseline.current.body || note.tags.join("\0") !== baseline.current.tags.join("\0"))) setConflict({ disk, mine: note }); else if (disk.revision !== baseline.current.revision) { baseline.current = disk; setNote(disk); setStatus("Updated from disk"); } } catch { /* file may have been moved or deleted */ } } }, 2500); return () => clearInterval(interval); }, [library, note?.path, note?.title, note?.body, note?.tags]);
  useEffect(() => { const onKeyDown = (event: KeyboardEvent) => { const mod = event.metaKey || event.ctrlKey; if (!mod) return; const key = event.key.toLowerCase(); if (key === "e" && note) { event.preventDefault(); setMode(value => value === "edit" ? "preview" : "edit"); } if (key === "n") { event.preventDefault(); void createNote(); } if (key === "k") { event.preventDefault(); document.querySelector<HTMLInputElement>("#note-search")?.focus(); } if (key === "p") { event.preventDefault(); setQuickOpen(true); } if (key === "s" && note) { event.preventDefault(); void saveNote(note); } if (key === "1") { event.preventDefault(); document.querySelector<HTMLButtonElement>(".new-note")?.focus(); } if (key === "2") { event.preventDefault(); document.querySelector<HTMLButtonElement>(".note-card")?.focus(); } if (key === "3") { event.preventDefault(); editor.current?.focus(); } if (event.key === "\\") { event.preventDefault(); setSidebarHidden(value => !value); } }; window.addEventListener("keydown", onKeyDown); return () => window.removeEventListener("keydown", onKeyDown); }, [note, library]);

  const selectLibrary = async () => { const selected = await open({ directory: true, multiple: false, title: "Choose your notes folder" }); if (typeof selected === "string") { localStorage.setItem(libraryKey, selected); setLibrary(selected); setActivePath(null); setFilter({ type: "all" }); } };
  const createNote = async () => { if (!library) return void await selectLibrary(); try { const created = await invoke<NoteDocument>("create_note", { libraryPath: library }); await refresh(); setActivePath(created.path); setStatus("New note created"); } catch (error) { setStatus(`Could not create note: ${String(error)}`); } };
  const saveNote = async (draft: NoteDocument) => { try { setStatus("Saving…"); const saved = await invoke<NoteDocument>("save_note", { note: draft }); if (activePathRef.current === saved.path) baseline.current = saved; setNote(current => current?.path === saved.path ? saved : current); await refresh(); setStatus("Saved"); } catch (error) { setStatus(`Save failed: ${String(error)}`); } };
  const addTag = (value: string) => { if (!note) return; const tag = value.trim().replace(/,$/, ""); if (!tag || tag.length > 64) return setStatus("Tags must be 1–64 characters"); if (!note.tags.some(existing => existing.toLowerCase() === tag.toLowerCase())) setNote({ ...note, tags: [...note.tags, tag] }); };
  const rename = async (name: string) => { if (!note) return; try { const renamed = await invoke<NoteDocument>("rename_note", { path: note.path, name }); baseline.current = renamed; setNote(renamed); setActivePath(renamed.path); await refresh(); setRenameOpen(false); } catch (error) { setStatus(`Rename failed: ${String(error)}`); } };
  const duplicate = async () => { if (!note) return; try { const copy = await invoke<NoteDocument>("duplicate_note", { path: note.path }); await refresh(); setActivePath(copy.path); } catch (error) { setStatus(`Duplicate failed: ${String(error)}`); } };
  const trash = async () => { if (!note || !library || !confirm(`Move “${note.title}” to this library’s trash?`)) return; try { await invoke("move_note_to_trash", { path: note.path, libraryPath: library }); setActivePath(null); await refresh(); } catch (error) { setStatus(`Could not move note: ${String(error)}`); } };
  const tagCounts = useMemo(() => notes.reduce<Record<string, number>>((counts, current) => { current.tags.forEach(tag => { const existing = Object.keys(counts).find(value => value.toLowerCase() === tag.toLowerCase()) || tag; counts[existing] = (counts[existing] ?? 0) + 1; }); return counts; }, {}), [notes]);
  const visibleNotes = useMemo(() => notes.filter(item => { const matchFilter = filter.type === "all" || (filter.type === "untagged" ? item.tags.length === 0 : item.tags.some(tag => tag.toLowerCase() === filter.tag?.toLowerCase())); return matchFilter && item.searchable_text.includes(query.toLowerCase()); }), [notes, filter, query]);
  const backlinks = useMemo(() => note ? notes.filter(item => item.path !== note.path && wikiTargets(item.searchable_text).some(target => target.toLowerCase() === note.title.toLowerCase())) : [], [notes, note]);
  const suggestions = useMemo(() => Object.keys(tagCounts).filter(tag => tag.toLowerCase().includes((document.activeElement as HTMLInputElement)?.value?.toLowerCase() || "")).slice(0, 6), [tagCounts, note]);
  const noteEditor = note ? <MarkdownEditor ref={editor} notePath={note.path} value={note.body} onChange={body => setNote(current => current?.path === note.path ? { ...current, body } : current)} onBlur={() => void saveNote(note)} autoFocus className="markdown-editor" /> : null;
  const notePreview = note ? <MarkdownPreview markdown={note.body} notePath={note.path} notes={notes} onOpen={setActivePath} /> : null;

  return <main className={`app-shell ${sidebarHidden || focusMode ? "sidebar-hidden" : ""} ${focusMode ? "focus-mode" : ""}`}>
    <aside className="sidebar" aria-label="Library navigation"><div className="brand"><span className="brand-mark">✦</span><span>Markdown Notes</span></div><button className="new-note" onClick={() => void createNote()}>＋ New note <kbd>{shortcut}N</kbd></button><label className="search"><span>⌕</span><input id="note-search" value={query} onChange={event => setQuery(event.target.value)} placeholder="Search notes" /></label><nav><button className={filter.type === "all" ? "nav-item selected" : "nav-item"} onClick={() => setFilter({ type: "all" })}><span>All notes</span><small>{notes.length}</small></button><button className={filter.type === "untagged" ? "nav-item selected" : "nav-item"} onClick={() => setFilter({ type: "untagged" })}><span>Untagged</span><small>{notes.filter(item => !item.tags.length).length}</small></button><p className="section-label">Tags</p>{Object.entries(tagCounts).sort(([a], [b]) => a.localeCompare(b)).map(([tag, count]) => <button key={tag} className={filter.type === "tag" && filter.tag?.toLowerCase() === tag.toLowerCase() ? "nav-item selected" : "nav-item"} onClick={() => setFilter({ type: "tag", tag })}><span># {tag}</span><small>{count}</small></button>)}</nav><div className="library-control"><button onClick={() => void selectLibrary()}>Open library</button><p title={library ?? undefined}>{library ? library.split(/[\\/]/).pop() : "No library selected"}</p></div></aside>
    <section className="note-list"><header><h1>{filter.type === "tag" ? `# ${filter.tag}` : filter.type === "untagged" ? "Untagged" : "All notes"}</h1><span>{visibleNotes.length}</span></header><div className="notes">{visibleNotes.map(item => <NoteListItem key={item.path} note={{ ...item, body: item.excerpt }} active={item.path === activePath} pinned={pinned.includes(item.path)} onOpen={selected => setActivePath(selected.path)} onTogglePin={selected => setPinned(value => value.includes(selected.path) ? value.filter(path => path !== selected.path) : [...value, selected.path])} />)}{library && !visibleNotes.length && <p className="empty-list">No matching notes yet.</p>}</div></section>
    <section className="workspace">{note ? <><header className="workspace-header"><div className="title-stack"><input className="note-title" aria-label="Note title" value={note.title} onChange={event => setNote({ ...note, title: event.target.value })} placeholder="Untitled" /><div className="note-file"><span title={note.path}>{fileStem(note.path)}.md</span><span role="status">{status}</span></div></div><div className="actions"><FocusModeToggle focused={focusMode} onChange={setFocusMode} hotkeyHint={`${shortcut}\\`} /><button title="Rename file" onClick={() => setRenameOpen(true)}>Rename file</button><button title="Duplicate note" onClick={() => void duplicate()}>Duplicate</button><button className={pinned.includes(note.path) ? "active-pin" : ""} onClick={() => setPinned(value => value.includes(note.path) ? value.filter(path => path !== note.path) : [...value, note.path])}>Pin</button><button className="danger" onClick={() => void trash()}>Trash</button><ViewModeControl mode={mode} onChange={setMode} hotkeyHint={`${shortcut}E`} /></div></header><div className="tag-editor">{note.tags.map(tag => <button key={tag} onClick={() => setNote({ ...note, tags: note.tags.filter(value => value !== tag) })}>#{tag} ×</button>)}<TagCombobox options={Object.keys(tagCounts)} selectedTags={note.tags} inputValue={tagInput} onInputValueChange={setTagInput} onAdd={addTag} /></div><div className={`note-content ${mode}`}>{mode === "edit" ? noteEditor : mode === "preview" ? notePreview : <ResizableSplit left={noteEditor} right={notePreview} minLeftWidth={280} minRightWidth={320} persistenceKey="markdown-notes.split-ratio" />}</div>{backlinks.length > 0 && <aside className="backlinks"><strong>Linked from</strong>{backlinks.map(item => <button key={item.path} onClick={() => setActivePath(item.path)}>{item.title}</button>)}</aside>}</> : <div className="welcome"><div className="welcome-icon">✦</div><h1>{library ? "Choose a note or create one" : "Your notes, in plain Markdown"}</h1><p>{library ? "Select a note from the list, or make a fresh one." : "Choose a folder. Your notes stay as files you can use anywhere."}</p><button className="primary" onClick={() => void (library ? createNote() : selectLibrary())}>{library ? "New note" : "Choose notes folder"}</button></div>}</section>
    {quickOpen && <QuickSwitcher notes={notes} onClose={() => setQuickOpen(false)} onSelect={selected => { setActivePath(selected.path); setQuickOpen(false); }} />}{renameOpen && note && <RenameDialog name={fileStem(note.path)} onClose={() => setRenameOpen(false)} onSave={rename} />}{conflict && <ConflictDialog conflict={conflict} onChoose={choice => { if (choice === "disk") { baseline.current = conflict.disk; setNote(conflict.disk); } else { baseline.current = conflict.disk; void saveNote(conflict.mine); } setConflict(null); }} />}
  </main>;
}

function excerpt(item: NoteSummary, query: string) { const text = item.searchable_text.replace(/\s+/g, " "); const at = text.indexOf(query.toLowerCase()); return at < 0 ? "" : `${at > 45 ? "…" : ""}${text.slice(Math.max(0, at - 45), at + query.length + 90)}${at + query.length + 90 < text.length ? "…" : ""}`; }
function MarkdownPreview({ markdown, notePath, notes, onOpen }: { markdown: string; notePath: string; notes: NoteSummary[]; onOpen: (path: string) => void }) { const resolved = markdown.replace(/\[\[([^\]|]+)(?:\|([^\]]+))?\]\]/g, (_, title, label) => `[${label || title}](note:${encodeURIComponent(title.trim())})`); const directory = notePath.replace(/[\\/][^\\/]+$/, ""); const localAsset = (src?: string) => !src || /^(https?:|data:|asset:)/i.test(src) ? src : convertFileSrc(`${directory}/${src}`); return <article className="preview"><ReactMarkdown remarkPlugins={[remarkGfm, normalizeCodeLanguages]} rehypePlugins={[rehypeHighlight]} components={{ a: ({ href, children }) => { if (href?.startsWith("note:")) { const title = decodeURIComponent(href.slice(5)); const target = notes.find(item => item.title.toLowerCase() === title.toLowerCase()); return <a href={href} onClick={event => { event.preventDefault(); if (target) onOpen(target.path); }}>{children}</a>; } return <a href={href} target="_blank" rel="noreferrer">{children}</a>; }, img: ({ src, alt }) => <img src={localAsset(src)} alt={alt || ""} /> }}>{resolved}</ReactMarkdown></article>; }
function normalizeCodeLanguages() { return (tree: MarkdownNode) => { const visit = (node: MarkdownNode) => { if (node.type === "code" && node.lang) node.lang = node.lang.toLowerCase(); node.children?.forEach(visit); }; visit(tree); }; }
function RenameDialog({ name, onClose, onSave }: { name: string; onClose: () => void; onSave: (name: string) => void }) { const [value, setValue] = useState(name); return <div className="modal-backdrop"><form className="modal" onSubmit={event => { event.preventDefault(); onSave(value); }}><h2>Rename file</h2><input aria-label="File name" autoFocus value={value} onChange={event => setValue(event.target.value)} /><div><button type="button" onClick={onClose}>Cancel</button><button className="primary">Rename file</button></div></form></div>; }
function ConflictDialog({ conflict, onChoose }: { conflict: Conflict; onChoose: (choice: "mine" | "disk") => void }) { return <div className="modal-backdrop"><section className="modal conflict"><h2>This note changed outside the app</h2><p>Your unsaved edits have not been overwritten. Choose which version to keep.</p><details><summary>Compare versions</summary><div className="compare"><pre>{conflict.mine.body}</pre><pre>{conflict.disk.body}</pre></div></details><div><button onClick={() => onChoose("disk")}>Use disk version</button><button className="primary" onClick={() => onChoose("mine")}>Keep my edits</button></div></section></div>; }
createRoot(document.getElementById("root")!).render(<React.StrictMode><App /></React.StrictMode>);
